### ISSUE TITLE
Update wrong zone name

### ISSUE THREAD

**Issue by aeroreyna** [michaelkourlas/node-cloudflare-dynamic-dns#7] opened 2017-05-23 16:10 UTC
Hello everyone.

I'm using this tool to update my dns configuration of two sites with one account in cloudflare.
Nevertheless only one of my sites gets updated right. Let's call it site1.com. Therefore site1.com has the right ip, thanks to you guys. But my site2.com do no change, but instead the records of site1.com get updated by adding a new site2.com.site1.com every time.

I'm using the right name and zone name for each one, and running each update in it own process.

Is it a problem an known issue in this tool or can I be doing something wrong?

**Comment by michaelkourlas** [comment] 2019-02-23 04:04
I believe this is a duplicate of #5.

**Closed as completed by michaelkourlas** 2019-02-23 04:04 UTC
Labels: duplicate
